Improve-actions (#12)
* improve ci workflow, with over complex skip input (as a more future proof solution for skipping tests and testcases as retryer's tests currently will infintely yield because of a lune bug)
* add concurrency to docs workflow
* add type for tag name arg in release workflow
* simplify create draft step of release workflow
* remove usages of foreman, and replace with rokit

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,6 +2,11 @@ name: CI
 
 on:
   workflow_dispatch:
+    inputs:
+      skip:
+        description: 'Test cases to skip (format: LIBNAME.TESTCASE or LIBNAME(...TESTCASE))'
+        required: false
+        type: string
   push:
     branches: [ main ]
     paths:
@@ -14,40 +19,108 @@ on:
       - "testkit.luau"
 
 jobs:
-  run-tests:
+  parse_skips:
+    name: Parse skips
+    if: inputs.skip
+    runs-on: ubuntu-latest
+    concurrency:
+      group: CI-PARSE-${{ github.workflow }}-${{ github.ref }}
+      cancel-in-progress: true
+    outputs:
+      skip_json: ${{ steps.main.outputs.skip_json }}
+
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: main
+        id: main
+        shell: bash
+        run: |
+          skip_json="{}"
+
+          # Remove all whitespace and then split
+          IFS=',' read -ra SKIP_ITEMS <<< "$(echo "${{ inputs.skip }}" | tr -d '[:space:]')"
+
+          for item in "${SKIP_ITEMS[@]}"; do
+            if [[ $item =~ ^([A-Za-z0-9_]+)\(([A-Za-z0-9_,]+)\)$ ]]; then
+              lib="${BASH_REMATCH[1]}"
+              IFS=',' read -ra cases <<< "${BASH_REMATCH[2]}"
+              
+              for case in "${cases[@]}"; do
+                if [[ ! $case =~ ^[A-Za-z0-9_]+$ ]]; then
+                  echo "SYNTAX ERROR INVALID CASE NAME '$case' IN LIB '$item'"
+                  exit 1
+                else
+                  skip_json=$(echo $skip_json | jq --arg lib "$lib" --arg case "$case" '. + {($lib): (.[($lib)] + [$case] | unique)}')
+                fi
+              done
+            elif [[ $item =~ ^([A-Za-z0-9_]+)\.([A-Za-z0-9_]+)$ ]]; then
+              lib="${BASH_REMATCH[1]}"
+              case="${BASH_REMATCH[2]}"
+              skip_json=$(echo $skip_json | jq --arg lib "$lib" --arg case "$case" '. + {($lib): (.[($lib)] + [$case] | unique)}')
+            else
+              echo "SYNTAX ERROR INVALID FORMAT GIVEN FOR '$item'"
+              exit 1
+            fi
+          done
+          
+          echo "skip_json=$(echo $skip_json | jq -c .)" >> $GITHUB_OUTPUT
+
+  Run:
+    needs: parse_skips
+    env:
+      SKIP_JSON: ${{ needs.parse_skips.outputs.skip_json }}
+    
     strategy:
-        fail-fast: false
-        matrix:
-          include:
-            - name: Windows x86_64
-              runner-os: windows-latest
+      fail-fast: false
+      matrix:
+        include:
+          - name: Windows
+            runner-os: windows-latest
   
-            - name: Linux x86_64
-              runner-os: ubuntu-latest
+          - name: Linux
+            runner-os: ubuntu-latest
   
-            - name: macOS aarch64
-              runner-os: macos-14
-    name: ${{ matrix.name }}
+          - name: macOS
+            runner-os: macos-14
+    concurrency:
+      group: CI-${{ matrix.runner-os }}-${{ github.workflow }}-${{ github.ref }}
+      cancel-in-progress: true
     runs-on: ${{ matrix.runner-os }}
+    name: ${{ matrix.name }}
         
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-
-      - name: Setup Foreman
-        uses: Roblox/setup-foreman@v1
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
+      - uses: CompeyDev/setup-rokit@v0.1.0
+      - uses: actions/checkout@v3
 
       - name: Install Toolchain
-        run: foreman install
+        run: rokit install --no-trust-check
+
+      - name: Append skips
+        if: inputs.skip
+        shell: bash
+        run: |
+          find libs -name "*test.luau" | while read -r file; do
+            echo "Running test: $file"
+            
+            # Extract lib name from filename
+            lib_name=$(basename "$file" | sed 's/\.test\.luau$//')
+            
+            skip_cases=$(echo $SKIP_JSON | jq -r --arg lib "$lib_name" '.[$lib] // [] | .[]')
+            
+            while IFS= read -r case; do
+              if [[ -n $case ]]; then
+                echo "SKIP(\"$case\")" >> "$file"
+              fi
+            done <<< "$skip_cases"
+          done
 
       - name: Run Tests
         shell: bash
         run: |
           find libs -name "*test.luau" | while read -r file; do
             # append the finish call to the end of the file, because im lazy!!
-            echo -e "\n\nassert(FINISH())" >> "$file"
+            echo "\n\nassert(FINISH())" >> "$file"
 
             lune run $file
           done
